name: Exemplo do Node
on: 
 push:
   branches:
   - main
 workflow_dispatch:
jobs:
  build-node:
    name: Build Node
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - run: node --version
      - run: npm --version
      - run: npm install
